version: "3.9"

services:
  primary_postgres:
    container_name: primary_postgres
    image: postgres:15
    hostname: primary_postgres
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    command: >
      bash -c "apt-get update && apt-get install -y postgresql-15-wal2json && exec docker-entrypoint.sh postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - iceberg_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "main", "-d", "main"]
      interval: 10s
      timeout: 5s
      retries: 10

  data-loader:
    image: postgres:15
    container_name: sample_data_loader
    environment:
      PGUSER: main
      PGPASSWORD: password
      PGDATABASE: main
    depends_on:
      primary_postgres:
        condition: service_healthy
    entrypoint: >
      bash -c " 
        echo \"Waiting for Postgres to be ready...\"; 
        until pg_isready -h primary_postgres -p 5432 -U main -d main; do 
          echo \"Waiting...\"; 
          sleep 2; 
        done; 
        echo \"Creating test table sample_data...\"; 
        psql -h primary_postgres -U main -d main -c \"CREATE TABLE IF NOT EXISTS sample_data (id SERIAL PRIMARY KEY, str_col TEXT, num_col INT);\"; 
        echo \"Inserting one test row...\"; 
        psql -h primary_postgres -U main -d main -c \"INSERT INTO sample_data (str_col, num_col) VALUES ('Hello world', 123);\"; 
        echo \"Creating orders table and inserting data...\"; 
        psql -h primary_postgres -U main -d main -c \\\"CREATE TABLE IF NOT EXISTS orders (id SERIAL PRIMARY KEY, product VARCHAR(100), quantity INT, price NUMERIC);\\\"; 
        psql -h primary_postgres -U main -d main -c \\\"INSERT INTO orders (product, quantity, price) VALUES
          ('Pen', 10, 1.5),
          ('Notebook', 5, 3.0),
          ('Pencil', 12, 0.8),
          ('Eraser', 7, 0.5),
          ('Phone', 8, 9.2),
          ('Laptop', 2, 15.0),
          ('Marker', 6, 2.0),
          ('Tablet', 3, 12.5),
          ('Charger', 4, 5.5),
          ('Backpack', 1, 25.0),
          ('Sticky Notes', 20, 0.7),
          ('Highlighter', 9, 1.2),
          ('Scissors', 2, 3.5),
          ('Glue Stick', 5, 0.9),
          ('USB Drive', 4, 6.0),
          ('Mouse', 3, 7.5),
          ('Keyboard', 2, 10.0),
          ('Monitor', 1, 30.0),
          ('Desk Lamp', 2, 13.0),
          ('Whiteboard', 1, 40.0);\\\"; 
        echo \"Creating logical replication slot...\"; 
        psql -h primary_postgres -U main -d main -c \"SELECT * FROM pg_create_logical_replication_slot('postgres_slot', 'wal2json');\"; 
        echo \"Done. Data and replication slot should now exist.\" 
      "
    restart: "no"
    networks:
      - iceberg_net

networks:
  iceberg_net:

volumes:
  pg-data:
